// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface TrueFoundryModelProvider {
    /** Models exposed by this provider (at least one). */
    models: TrueForge.ConfiguredModel[];
    type: "truefoundry";
}
