// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfiguredModel } from "./ConfiguredModel.js";

export const TrueFoundryModelProvider: core.serialization.ObjectSchema<
    serializers.TrueFoundryModelProvider.Raw,
    TrueForge.TrueFoundryModelProvider
> = core.serialization.object({
    models: core.serialization.list(ConfiguredModel),
    type: core.serialization.stringLiteral("truefoundry"),
});

export declare namespace TrueFoundryModelProvider {
    export interface Raw {
        models: ConfiguredModel.Raw[];
        type: "truefoundry";
    }
}
